#!/system/bin/sh


if [ -d "/data/media/0" ]; then
    INT="/data/media/0"
elif [ -d "/storage/emulated/0" ]; then
    INT="/storage/emulated/0"
else
    INT="/sdcard"
fi

# ---------------------------------------------------------------------#

if ! { mkdir -p "/data/local/tmp/x" || install -d "/data/local/tmp/x"; }; then
    echo "Error 0"
    exit 1
fi

# ---------------------------------------------------------------------#

TMP="/data/local/tmp/x"

P1="$INT/"

P2="$INT/"


# ---------------------------------------------------------------------#

if [ -d "$P1" ]; then
    DIR1="$P1"
else
    DIR1="/data/local/x"
fi

# ---------------------------------------------------------------------#

if [ -d "$P2" ]; then
    DIR2="$P2"
else
    DIR2="/data/local/x"
fi

# ---------------------------------------------------------------------#


if [ "$DIR1" = "$TMP" ] && [ "$DIR2" = "$TMP" ]; then
    echo "0 K"
elif [ "$DIR1" != "$TMP" ] && [ "$DIR2" != "$TMP" ]; then
    du -hcs "$DIR1" "$DIR2" | grep total | cut -f1
elif [ "$DIR1" = "$TMP" ] && [ "$DIR2" != "$TMP" ]; then
    du -hcs "$DIR2" | grep total | cut -f1
elif [ "$DIR2" = "$TMP" ] && [ "$DIR1" != "$TMP" ]; then
    du -hcs "$DIR1" | grep total | cut -f1
fi
# ---------------------------------------------------------------------#
                      rm -rf /data/local/x
# ---------------------------------------------------------------------#