#!/system/bin/sh

if [ -d "/data/media/0" ]; then
    INT="/data/media/0"
elif [ -d "/storage/emulated/0" ]; then
    INT="/storage/emulated/0"
else
    INT="/sdcard"
fi

# ---------------------------------------------------------------------#

if ! { mkdir -p "/data/local/x" || install -d "/data/local/x"; }; then
    echo "Error 0"
    exit 1
fi

# ---------------------------------------------------------------------#


P1="$INT/B/X"

P2="$INT/B/Y Z"


# ---------------------------------------------------------------------#

if [ -d "$P1" ]; then
    DIR1="$P1"
else
    DIR1="/data/local/x"
fi

# ---------------------------------------------------------------------#

if [ -d "$P2" ]; then
    DIR2="$P2"
else
    DIR2="/data/local/x"
fi

# ---------------------------------------------------------------------#


if [ -d "$DIR1" ] && [ -d "$DIR2" ]; then
    du -hcs "$DIR1" "$DIR2" | grep total | cut -f1
else
    echo "Error 1"
fi


# ---------------------------------------------------------------------#
                      rm -rf /data/local/x
# ---------------------------------------------------------------------#